# Generated by Django 6.0.1 on 2026-01-22 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userreview'),
    ]

    operations = [
        # Skip AddField operations for is_resolved and resolved_at
        # as they already exist in the database
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('teacher_name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('remark_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='api_borrowr_status_f8e94c_idx'), models.Index(fields=['student_id', '-created_at'], name='api_borrowr_student_f0e546_idx')],
            },
        ),
        migrations.CreateModel(
            name='BorrowRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_key', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('item_image', models.CharField(blank=True, max_length=500, null=True)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.borrowrequest')),
            ],
        ),
    ]
