# Generated by Django 6.0.1 on 2026-01-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userreview_is_resolved_userreview_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20),
        ),
    ]
