# Generated by Django 6.0.1 on 2026-01-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_borrowrequestitem_status_userreview_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestitem',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequestitem',
            name='remark_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequestitem',
            name='remark_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
