# Generated by Django 6.0.1 on 2026-02-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_borrowrequestitem_admin_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestitem',
            name='actual_returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
